[av]
; Unconditionally silence the beeper
silence_beeper = false

[ble]
; BLE enabled by manufacturer
mfg_enabled = true
; BLE enabled by client
client_enabled = true
; Timeout for a no-activity disconnect
connection_timeout_ms = 10000
; Allow firmware updates over BLE
allow_fw_updates = true

[ble/adv_params]
; Minimum Advertising Interval (N * 0.625 milliseconds)
; Range: 0x0020 to 0x4000
interval_min = 48 ; 30ms
; Maximum Advertising Interval (N * 0.625 milliseconds)
; Range: 0x0020 to 0x4000
interval_max = 96 ; 60ms
; Bit-field of advertising options
; 0x0001 - Advertise as connectable
; 0x0002 - Advertise one time
; 0x0004 - Advertise using identity address
; 0x0010 - Low duty cycle directed advertising
; 0x0020 - Directed advertising to privacy-enabled peer
; 0x0040 - Use filter accept list to filter devices that can request scan response data
; 0x0080 - Use filter accept list to filter devices that can connect
; 0x0100 - Notify the application when a scan response data has been sent to an active scanner
options = 0x0001

[ble/adv_data/values]
; Flags advertising data value
flags = 0x6
; Tx Power advertising data value
tx_power = -16
; UUID128 complete advertising data value
uuid128_all = "9fdc9c81fffe7fbfe5112caf1ad82034"

[ble/adv_data/order]
; Flags advertising data order (<=0 to not include)
flags = 1
; Tx Power advertising data order (<=0 to not include)
tx_power = 2
; UUID128 complete advertising data order (<=0 to not include)
uuid128_all = 3

[ble/scan_data/values]
; Name complete scan response data value
name_complete = "APEX"

[ble/scan_data/order]
; Name complete scan response data order (<= 0 to not include)
name_complete = 1

[ble/configure]
; Communicate with Configure application using secure transactions
secure_transactions = true
; Allow credentials to be sent via Configure application (legacy commands)
allow_credentials = true
; Convert credentials to BCD format
bcd_credentials = false

[ble/av]
; Allow BLE to override OSDP LEDs during connection
override_osdp_leds = true
; A/V color to set upon BLE connection
; Supported colors:
; - "off"
; - "red"
; - "green"
; - "blue"
; - "amber"
; - "magenta"
; - "white"
color = "amber"
; Set A/V to solid (false) or blinking (true)
is_blinking = false
; A/V blinking on/off period
blinking_period = 0

[card_tracker]
; Upon a card scan, card UID will be added to an anti-passback to not continuously send the card credentials. This determines if active.
enabled = true
; Maximum number of cards able to track at a time (up to 15)
max_cards = 4
; Anti-passback timeout
timeout_ms = 5000

[host_communication]
; Host communication mode
; Supported options:
; - "auto_detect"
; - "osdp"
; - "wiegand"
mode = "auto_detect"

[keypad]
; State of LEDs by default, while when system is idle
idle_led_on = true
; State the keypad LEDs briefly pulse when a key is pressed
pressed_led_on = false

; Both NFC and BLE MyPass settings
[mypass]
; Allow credentials to be sent via MyPass application
allow_credentials = true
; Convert credentials to BCD format
bcd_credentials = false
; Master key 1
km1_se_slot_nb = 24
; Master key 2
km2_se_slot_nb = 25
; Credential key 1
kc1_se_slot_nb = 26
; Credential key 2
kc2_se_slot_nb = 27
; Enable keyset 1 and 2
all_keys = true
; Metadata to be sent via MyPass application (4-bytes)
metadata = "00000000"
; Allow key rolling
allow_key_rolling = true

[rfid]
; Delay between polling RFID technologies (and NFC types)
poll_timeout_ms = 100

[rfid/av]
; Upon a card scan, beep occurs (or not)
beep_enabled = true
; Upon a card scan, LED flash occurs (or not)
led_enabled = true
; Upon a card scan, LED and beep occurs for this duration
duration_ms = 160
; Upon a card scan, LED flashes this color
; Supported colors:
; - "off"
; - "red"
; - "green"
; - "blue"
; - "amber"
; - "magenta"
; - "white"
color = "green"

[rfid/hf/nfc]
; Determines if NFC polls technologies
enabled = true
; Enabled NFC protocols.
; Characters indicate the NFC type to enable:
; - 'A' - ISO14443-A
; - 'B' - ISO14443-B
; - 'F' - FeliCa
; - 'V' - ISO/PICO15693
enabled_protocols = "ABFV"
; After polling for an NFC device, immediately starts polling another NFC technology. Otherwise delays for @ref rfid_settings_data @p poll_timeout_ms
accel_polling = false
; Upon startup, NFC IC should perform auto tuning. Otherwise manually tuned.
auto_tune = true
; NFC baudrate in Kbps.
; Supported rates:
; - 106
; - 212
; - 424
; - 848
baudrate = 106
; Upon an NFC SELECT, delay 5ms + this value
ext_select_delay_ms = 0
; Time after a power cycle before config card application is disabled
config_card_timeout_min = 1
; Upon reading card credentials, the CSN is appended to the end
append_csn = false

[rfid/hf/app/csn]
; CSN card handling enabled
enabled = true
; (values are encoded where the MSB is the bit-length. The LSB is the encoding type)
; Each of the following CSN formats have the following supported types:
; 0x0000: as-is (no formatting update)
; 0x1A00: 26-bit
;   - 0x1A00: XOR
;     - bitstream starts at [0].bit0
;     - [0]: 0x00 or 0x01 (based on even parity over 12-bits into bit-7 of P)
;     - [1]: csn[0] ^ csn[3] ^ csn[6]
;     - [2]: csn[1] ^ csn[4] ^ csn[7]
;     - [3]: csn[2] ^ csn[5]
;     - [4]: 0x00 or 0x80 (based on odd parity)
; 0x2000: 32-bit
;   - 0x2000: LSB
;     - [0]: csn[0]
;     - [1]: csn[1]
;     - [2]: csn[2]
;     - [3]: csn[3]
;   - 0x2001: MSB
;     - [0]: csn[3]
;     - [1]: csn[2]
;     - [2]: csn[1]
;     - [3]: csn[0]
;   - 0x2003: LSB XOR
;     - [0]: csn[0]
;     - [1]: csn[1] ^ csn[4] ^ csn[7]
;     - [2]: csn[2] ^ csn[5] ^ csn[8]
;     - [3]: csn[3] ^ csn[6] ^ csn[9]
;   - 0x2004: MSB XOR
;     - [3]: csn[0]
;     - [2]: csn[1] ^ csn[4] ^ csn[7]
;     - [1]: csn[2] ^ csn[5] ^ csn[8]
;     - [0]: csn[3] ^ csn[6] ^ csn[9]
;   - 0x2005: Plus
;     - [0]: csn[0]
;     - [1]: csn[1]
;     - [2]: csn[2]
;     - [3]: csn[3] ^ csn[4]
; 0x2200: 34-bit
;   - 0x2200: MSB Parity
;     - bitstream starts at [0].bit0
;     - [0]: 0x00 or 0x01 (based on even parity into bit-7 of P)
;     - [1]: csn[3] ^ csn[6] ^ csn[9]
;     - [2]: csn[2] ^ csn[5] ^ csn[8]
;     - [3]: csn[1] ^ csn[4] ^ csn[7]
;     - [4]: csn[0]
;     - [5]: 0x00 or 0x80 (based on odd parity)
; 0x2800: 40-bit
;   - 0x2800: MSB
;     - [0]: (csn[4] & 0x3F) | (0x00 or 0x40) (based on even parity over 19-bits into bit-6 of P)
;     - [1]: csn[3]
;     - [2]: csn[2]
;     - [3]: csn[1]
;     - [4]: csn[0]
;     - [5]: 0x00 or 0x80 (based on odd parity)
;   - 0x2801: MSB LRC OR PCSC
;     - [0]: csn[3] ^ csn[6] ^ csn[9]
;     - [1]: csn[2] ^ csn[5] ^ csn[8]
;     - [2]: csn[1] ^ csn[4] ^ csn[7]
;     - [3]: csn[0]
;     - [4]: [0] ^ [1] ^ [2] ^ [3] (across formatted CSN)
; 0x3700: 55-bit
;   - 0x3700: MSB
;     - bitstream starts at [0].bit6
;     - [0]: (csn[6] & 0x1F) | (0x00 or 0x20) (based on even parity over 26-bits into bit-5 of P)
;     - [1]: csn[5]
;     - [2]: csn[4]
;     - [3]: csn[3]
;     - [4]: csn[2]
;     - [5]: csn[1]
;     - [6]: csn[0]
;     - [7]: 0x00 or 0x80 (based on odd parity)
; 0x3800: 56-bit
;   - 0x3800: LSB
;     - [0]: csn[0]
;     - [1]: csn[1]
;     - [2]: csn[2]
;     - [3]: csn[3]
;     - [4]: csn[4]
;     - [5]: csn[5]
;     - [6]: csn[6]
;   - 0x3800: MSB
;     - [0]: csn[6]
;     - [1]: csn[5]
;     - [2]: csn[4]
;     - [3]: csn[3]
;     - [4]: csn[2]
;     - [5]: csn[1]
;     - [6]: csn[0]
; 0x4000: 64-bit
;   - 0x4000: MSB
;     - [0]: csn[7]
;     - [1]: csn[6]
;     - [2]: csn[5]
;     - [3]: csn[4]
;     - [4]: csn[3]
;     - [5]: csn[2]
;     - [6]: csn[1]
;     - [7]: csn[0]
; 0x4B00: 75-bit
;   - 0x4B00: PCSC
;     - convert to BCD (12-characters, )
;     - [0]: 0x0B (start character)
;     - [1:12]: BCD[0:11]
;     - [13]: 0x0F (end character)
;     - [14]: 0x00 (reset LRC)
;     - compute parity and LRC
; Format to reassemble CSN when read a 4-byte type-A CSN
iso14443a_cl1_format = 0x0000
; Format to reassemble CSN when read a !4-byte type-A CSN
iso14443a_cl2_format = 0x0000
; Format to reassemble CSN when read a type-B CSN
iso14443b_format = 0x0000
; Format to reassemble CSN when read a type-F CSN
felica_format = 0x0000
; Format to reassemble CSN when read a type-V ISO CSN
iso15693_format = 0x0000
; Format to reassemble CSN when read a type-V PICO CSN
pico15693_format = 0x0000

[rfid/hf/app/meridian]
; Apple Wallet app handling and ECP polling enabled
enabled = false
; VASUP format (0x1 or 0x2)
selected_format = 0x2
; (applicable if `selected_format`=0x1) Indicates the operating mode.
; - 0x0: Terminal in VAS App OR Payment Mode
; - 0x1: Terminal in VAS App AND Payment Mode
; - 0x2: Terminal in VAS App Only Mode
; - 0x3: Terminal in Payment Mode Only
terminal_mode = 0x0
; | b8 | b7 | b6 | b5 | b4 | b3 | b2 | b1 | Description                               |
; | -- | -- | -- | -- | -- | -- | -- | -- | ----------------------------------------- |
; | 0  | -  | -  | -  | -  | -  | -  | -  | VAS Supported                             |
; | 1  | -  | -  | -  | -  | -  | -  | -  | VAS Not Supported                         |
; | -  | 0  | -  | -  | -  | -  | -  | -  | User Auth Requested                       |
; | -  | 1  | -  | -  | -  | -  | -  | -  | User Auth Not Requested                   |
; | -  | -  | -  | -  | L  | L  | L  | L  | Length of Terminal Type Data field (0-15) |
; | x  | x  | 0  | 0  | x  | x  | x  | x  | Bit b6 and b5 shall be set to 0           |
; - Length of Terminal Type Data field should always be 0x3
terminal_info = 0xC3
; if `selected_format`=0x1:
; - bit-field indicating the reader/terminal type
; | b8 | b7 | b6 | b5 | b4 | b3 | b2 | b1 | Description                                   |
; | -- | -- | -- | -- | -- | -- | -- | -- | --------------------------------------------- |
; | 0  | -  | -  | -  | -  | -  | -  | -  | VAS Supported                                 |
; | 1  | -  | -  | -  | -  | -  | -  | -  | VAS Not Supported                             |
; | -  | 0  | -  | -  | -  | -  | -  | -  | User Auth Requested                           |
; | -  | 1  | -  | -  | -  | -  | -  | -  | User Auth Not Requested                       |
; | -  | -  | -  | -  | 0  | 0  | 0  | 0  | Payment Terminal                              |
; | -  | -  | -  | -  | 0  | 0  | 0  | 1  | Transit Terminal (deprecated - use Format V2) |
; | -  | -  | -  | -  | 0  | 0  | 1  | 0  | Access Terminal (deprecated - use Format V2)  |
; | -  | -  | -  | -  | 0  | 0  | 1  | 1  | GymKit Handoff Terminal                       |
; | -  | -  | -  | -  | 1  | 1  | 1  | 1  | Other Terminal                                |
; | x  | x  | 0  | 0  | x  | x  | x  | x  | Bit b6 and b5 shall be set to 0               |
; if `selected_format`=0x2:
; - Value indicating the reader/terminal type (WaveLynx assigned 0x2)
; - Apple assigned WaveLynx the value 0x2
terminal_type = 0x02
; (applicable if `selected_format`=0x2) Indicates the reader/terminal subtype
; Apple assigned WaveLynx the following subtypes:
; - 0x0: University
; - 0x2: Corporate
; - 0x3: Hospitality
; - 0x4: Residential
terminal_subtype = 0x2
; (applicable if `selected_format`=0x2) Indicates the reader/terminal ID
; - Provide hexstring (up to 3-bytes)
terminal_id = "010203"
; Indicates the number of bits to send for a credential
bit_nb = 128
; Indicates if the privacy key should be diversified
diversify_privacy_key = false
; Convert credentials to BCD format
bcd_format = false

[rfid/hf/app/mifare_2go/generic]
; Mifare 2GO (Generic) application handling enabled
enabled = false
; Convert credentials to BCD format
bcd_format = false

[rfid/hf/app/mifare_2go/leaf]
; Mifare 2GO (Leaf) application handling enabled
enabled = false
; Convert credentials to BCD format
bcd_format = false

[rfid/hf/app/leaf]
; LEAF application handling enabled
enabled = false
; Upon reading legacy (Si/Cc) LEAF credential data, check the file signature
check_legacy_signature = true

[rfid/hf/app/leaf/1]
; Application handling enabled
enabled = true
; LEAF application ID
; - Provide hexstring (exactly 3-bytes)
app_id = "F51CDB" ; LEAF Si ACD 1
; DESFire card key number for authentication (0-13)
card_key_nb = 1
; Secure element key number for authentication
se_key_nb = 6

[rfid/hf/app/leaf/2]
; Application handling enabled
enabled = false
; See rfid/hf/leaf/1 if enabling
app_id = "000000"
card_key_nb = 0
se_key_nb = 0

[rfid/hf/app/leaf/3]
; Application handling enabled
enabled = false
; See rfid/hf/leaf/1 if enabling
app_id = "000000"
card_key_nb = 0
se_key_nb = 0

[rfid/hf/app/leaf/4]
; Application handling enabled
enabled = false
; See rfid/hf/leaf/1 if enabling
app_id = "000000"
card_key_nb = 0
se_key_nb = 0

[rfid/hf/app/mypass]
; MyPass application handling enabled
enabled = false

[rfid/hf/app/visa]
; Visa application handling enabled
enabled = false
; Sector number to read from
sector = 9
; Secure element key number for authentication
se_key_nb = 30

[rfid/hf/app/software_house/classic]
; Software House (MIFARE Classic) application handling enabled
enabled = false
; Sector number to read from
sector = 4
; Secure element key number for authentication
se_key_nb = 30
; Start bit index to read from within block
start_bit = 0
; Number of bits to read from start_bit within block
num_bits = 128
; Use KeyB for authentication (otherwise KeyA)
use_key_b = false

[rfid/hf/app/software_house/desfire]
; Software House (MIFARE DESFire) application handling enabled
enabled = false

[rfid/hf/app/fidelity]
; Fidelity application handling enabled
enabled = false
; Sector number to read from
sector = 2
; Secure element key number for authentication
auth_se_key_nb = 30
; Secure element key number for diversification
div_se_key_nb = 31
; Diversify key (otherwise use auth_key)
diversify_key = true
; Use KeyB for authentication (otherwise KeyA)
use_key_b = false

[rfid/hf/app/smartmax/classic]
; Smartmax (MIFARE Classic) application handling enabled
enabled = false
; Secure element key number for authentication
se_key_nb = 30
; Convert credentials to BCD format
bcd_format = false

[rfid/hf/app/smartmax/desfire]
; Smartmax (MIFARE DESFire) application handling enabled
enabled = false
; Convert credentials to BCD format
bcd_format = false

[rfid/hf/app/vanderbilt/classic]
; Vanderbilt (MIFARE Classic) application handling enabled
enabled = false
; Secure element key number for authentication
se_key_nb = 30

[rfid/hf/app/vanderbilt/desfire]
; Vanderbilt (MIFARE DESFire) application handling enabled
enabled = false
; Secure element key number for authentication
se_key_nb = 31

;[rfid/hf/piv]
;; Number of credential PIV bits to send
;acd_bit_nb = 40
;; Reassemble PIV data to BCD
;acd_bcd = false
;; (applicable if acd_bcd=true) Reverse BCD nibbles
;acd_reverse = false
;; Send bitstream containing GUID (otherwise FASC-N)
;force_guid = false
;; Respond with VSTAT on first Continue status command
;vstat_reply = false
;; Include TLV header in the Challenge response
;include_tlv_header = false
;; A single KEEP_ACTIVE command extends the RF activity persistently (instead of 8s max)
;ext_rf_persist = false

[tamper]
; Enable the ability to report tamper over Wiegand
wiegand_reporting_enabled = true
; Enable the ability to report tamper over OSDP
osdp_reporting_enabled = true
; Force the beeper on during OSDP tamper. When disabled
; wait for OSDP incoming message to turn on beeper
beeper_during_osdp_enabled = false
; Only report tamper on state change.
; When disabled, report tamper at sample frequency.
report_state_change_only_enabled = false
; Number of sequently tamper actuve checks before
; entering a tamper active state
num_reads_enter_active = 5
; Number of sequently tamper inactive checks before
; entering a tamper inactive state
num_reads_enter_inactive = 1
; Frequency, in ms, to check for a tamper
sample_frequency_ms = 200

[tamper/accel]
; How sensitively the accelerometer trips a tamper event
; Supported options:
; - "high"
; - "default"
; - "low"
sensitivity = "default"
; Enabled x-axis accelerometer for tamper detection
x_axis_enabled = true
; Enabled y-axis accelerometer for tamper detection
y_axis_enabled = true
; Enabled z-axis accelerometer for tamper detection
z_axis_enabled = true

[keys]
config_key = GENERIC:ZEROS_KEY
slot01 = GENERIC:ZEROS_KEY
slot02 = GENERIC:ZEROS_KEY
slot03 = GENERIC:ZEROS_KEY
slot04 = GENERIC:ZEROS_KEY
slot05 = GENERIC:ZEROS_KEY
slot06 = GENERIC:ZEROS_KEY
slot07 = GENERIC:ZEROS_KEY
slot08 = GENERIC:ZEROS_KEY
slot09 = GENERIC:ZEROS_KEY
slot10 = GENERIC:ZEROS_KEY
slot11 = GENERIC:ZEROS_KEY
slot12 = GENERIC:ZEROS_KEY
slot13 = GENERIC:ZEROS_KEY
slot14 = GENERIC:ZEROS_KEY
slot15 = GENERIC:ZEROS_KEY
slot16 = GENERIC:ZEROS_KEY
slot17 = GENERIC:ZEROS_KEY
slot18 = GENERIC:ZEROS_KEY
slot19 = GENERIC:ZEROS_KEY
slot20 = GENERIC:ZEROS_KEY
slot21 = GENERIC:ZEROS_KEY
slot22 = GENERIC:ZEROS_KEY
slot23 = GENERIC:ZEROS_KEY
slot24 = GENERIC:ZEROS_KEY
slot25 = GENERIC:ZEROS_KEY
slot26 = GENERIC:ZEROS_KEY
slot27 = GENERIC:ZEROS_KEY
slot28 = GENERIC:ZEROS_KEY
slot29 = GENERIC:ZEROS_KEY
slot30 = GENERIC:ZEROS_KEY
slot31 = GENERIC:ZEROS_KEY
slot32 = GENERIC:ZEROS_KEY
slot33 = GENERIC:ZEROS_KEY
slot34 = GENERIC:ZEROS_KEY
slot35 = GENERIC:ZEROS_KEY
slot36 = GENERIC:ZEROS_KEY
slot37 = GENERIC:ZEROS_KEY
slot38 = GENERIC:ZEROS_KEY
slot39 = GENERIC:ZEROS_KEY
slot40 = GENERIC:ZEROS_KEY
slot41 = GENERIC:ZEROS_KEY
slot42 = GENERIC:ZEROS_KEY
slot43 = GENERIC:ZEROS_KEY
slot44 = GENERIC:ZEROS_KEY
slot45 = GENERIC:ZEROS_KEY
slot46 = GENERIC:ZEROS_KEY
slot47 = GENERIC:ZEROS_KEY
slot48 = GENERIC:ZEROS_KEY
slot49 = GENERIC:ZEROS_KEY
slot50 = GENERIC:ZEROS_KEY