import features as wl
import standardTypes
import csv
import sys
import re
import os
import requests
import json
import base64
import yaml
import binascii
from urllib3.exceptions import InsecureRequestWarning
from datetime import date
import ast

def safe_int_eval(val):
    val = str(val).strip()

    if val == '':
        return 0
    
    try:
        # Attempt standard base-10 integer conversion first
        return int(val)
    except ValueError:
        try:
            # Safely parse complex code structures like '1 << 8' or bitwise shifts
            return int(ast.literal_eval(val))
        except Exception:
            # Fallback handle standalone operators/broken inputs gracefully without crashing the pipeline
            if "<<" in val:
                clean_val = val.lstrip('< ').strip()
                if clean_val.isdigit():
                    return 1 << int(clean_val)
            raise

# Suppress only the single warning from urllib3 needed.
requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning)

hw_types = [2, 3, 5, 6, 7]

PROD_TEST_ENC_KEY = "ETHOS_PT:keyID_4_a"
config = standardTypes.system_features()
SEQUOIA_IP = "10.1.10.14"
SEQUOIA_PORT = 443
# SEQUOIA_IP = "localhost"
# SEQUOIA_PORT = 1443
uri = "https://" + SEQUOIA_IP + ":" + str(SEQUOIA_PORT) + "/load_blob"
BASE_URL = "https://" + SEQUOIA_IP + ":" + str(SEQUOIA_PORT) + "/"


# # test setting all values to see formatting
# for x in range (64):
#     config.setOpt(x,x)
#
# config.enableAskSupport()
# config.setOpt(features.OPERATION_INDEX, features.ENABLE_ASK_RF)
# config.setVersion(1,2,3)


def sendToSequoia(operation, config, data):
    pass


def AddKeys(config):
    sendToSequoia("AddKeys", "configName", config)


def decomment(csvfile):
    for row in csvfile:
        raw = row.split("#")[0].strip()
        if raw:
            yield raw


def _verify_success(rsp):
    content = rsp.json()
    return (rsp.status_code == 200) and ("status" in content) and (content["status"] == "ok")


def write_user_keys(rsp):
    keyfile = open("UserKeys.c", mode="w")
    keyfile.write(
        "/* autogenerated Userkeys.c \n\
    */ \n\
const uint8_t UserKeys[END_OF_STD_KEYSETS][KEY_SET_SIZE] = \n\
{ \n"
    )
    NUM_KEYSETS = 16
    for keyset in range(NUM_KEYSETS):
        keyvalue = "\t{"
        for i in range(32):
            keyvalue += "0x{:02x},".format(rsp[i + (keyset * NUM_KEYSETS * 2)])
        keyvalue = keyvalue[0:-1] + "}"
        keyfile.write(keyvalue)
        keyfile.write("\n")
    keyfile.write("}\n")

    keyfile.close()


def load_blob(
    blob_id: str,
    name: str,
    desc: str,
    data: bytes,
    signing: str,
    signingkey: str,
    operations: list,
    keyset: list,
) -> tuple:
    body = {
        "id": blob_id,
        "name": name,
        "description": desc,
        "data": base64.b64encode(data).decode("utf-8"),
        "signing": signing,
        "signingkey": signingkey,
        "operations": operations,
        "keyset": keyset,
    }
    print("attempting to connect to sequoia")
    rsp = requests.post(BASE_URL + "load_blob", json=body, verify=False)
    print("finished connection attempt")
    if _verify_success(rsp):
        return True, base64.b64decode(rsp.json()["result"].encode("utf-8"))
    else:
        return False, None


if __name__ == "__main__":
    FEATURE_MANAGEMENT_READ_KEYSET = "GENERIC:ZEROS_KEY"
    FEATURE_MANAGEMENT_WRITE_KEYSET = "GENERIC:ZEROS_KEY"
    USER_APP_OCPSK_KEYSET = "GENERIC:ZEROS_KEY"
    USER_APP_READ_KEYSET = "GENERIC:ZEROS_KEY"
    USER_APP_CARD_MASTER_KEYSET = "GENERIC:ZEROS_KEY"
    USER_APP_CARD_WRITE_KEYSET = "GENERIC:ZEROS_KEY"
    EXT_MEM_KEYSET = "GENERIC:ZEROS_KEY"
    OSDP_KEYSET = "GENERIC:ZEROS_KEY"
    BLE_KEYSET = "GENERIC:ZEROS_KEY"
    MFC_KEYSET = "GENERIC:ZEROS_KEY"
    USER_APP2_K1_KEYSET = "GENERIC:ZEROS_KEY"
    USER_APP2_K2_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_IP_OCPSK_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_IP_READ_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_IP_CARD_MASTER_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_IP_CARD_WRITE_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_IP_KS1_OCPSK_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_IP_KS1_READ_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_IP_KS2_OCPSK_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_IP_KS2_READ_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_IP_KS3_OCPSK_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_IP_KS3_READ_KEYSET = "GENERIC:ZEROS_KEY"
    LEAF_KHSENC1_KEYS = "GENERIC:ZEROS_KEY"
    LEAF_KHSENC2_KEYS = "GENERIC:ZEROS_KEY"
    LEAF_HSREAD_KEYS = "GENERIC:ZEROS_KEY"
    LEAF_KBLEENC2_KEYS = "Lk00001:Kr34"
    NFC_KM1_KEYS = "GENERIC:ZEROS_KEY"
    NFC_KC1_KEYS = "GENERIC:ZEROS_KEY"
    NFC_KM2_KEYS = "GENERIC:ZEROS_KEY"
    NFC_KC2_KEYS = "GENERIC:ZEROS_KEY"
    NFC_MP0_KEYS = "GENERIC:ZEROS_KEY"
    NFC_MC0_KEYS = "GENERIC:ZEROS_KEY"

    config = standardTypes.system_features()
    if len(sys.argv) == 3:
        userkeys = sys.argv[2]
    else:
        userkeys = None
    with open(sys.argv[1], newline="") as csvfile:
        reader = csv.reader(decomment(csvfile))
        options = list(line for line in reader if line)
    # lookup = wl.lookup("BUILD_INDEX")
    # print (lookup)
    for setting in options:
        # if (setting[0] == "OPT"):
        # below might be a ticking time bomb eval() might be dangerous but since prefixed
        # with wl. might be safer ie no rm -rf / is possible
        # if (isinstance(setting[1],str) == True):
        keyset = ""
        # for now always

        enckey = "GENERIC:ZEROS"
        operation = setting[0].strip()
        if "FILTER" == operation:
            config.setFilter(
                setting[1].strip(), setting[2].strip(), setting[3].strip(), setting[4].strip()
            )
        elif "BLE_NAME" == operation:
            config.setBleName(setting[1].strip())
        # elif ( "KEYSET"== operation):
        #     keyset = setting[1].strip()
        elif "ENCKEY" == operation:
            enckey = setting[1].strip()
        elif "FEATURE_MANAGEMENT_READ_KEYSET" == operation:
            FEATURE_MANAGEMENT_READ_KEYSET = setting[1].strip()
        elif "FEATURE_MANAGEMENT_WRITE_KEYSET" == operation:
            FEATURE_MANAGEMENT_WRITE_KEYSET = setting[1].strip()
        elif "USER_APP_OCPSK_KEYSET" == operation:
            USER_APP_OCPSK_KEYSET = setting[1].strip()
        elif "USER_APP_READ_KEYSET" == operation:
            USER_APP_READ_KEYSET = setting[1].strip()
        elif "USER_APP_CARD_MASTER_KEYSET" == operation:
            USER_APP_CARD_MASTER_KEYSET = setting[1].strip()
        elif "USER_APP_CARD_WRITE_KEYSET" == operation:
            USER_APP_CARD_WRITE_KEYSET = setting[1].strip()
        elif "EXT_MEM_KEYSET" == operation:
            EXT_MEM_KEYSET = setting[1].strip()
        elif "OSDP_KEYSET" == operation:
            OSDP_KEYSET = setting[1].strip()
        elif "BLE_KEYSET" == operation:
            BLE_KEYSET = setting[1].strip()
        elif "MFC_KEYSET" == operation:
            MFC_KEYSET = setting[1].strip()
        elif "USER_APP2_K1_KEYSET" == operation:
            USER_APP2_K1_KEYSET = setting[1].strip()
        elif "USER_APP2_K2_KEYSET" == operation:
            USER_APP2_K2_KEYSET = setting[1].strip()
        elif "LEAF_IP_OCPSK_KEYSET" == operation:
            LEAF_IP_OCPSK_KEYSET = setting[1].strip()
        elif "LEAF_IP_READ_KEYSET" == operation:
            LEAF_IP_READ_KEYSET = setting[1].strip()
        elif "LEAF_IP_CARD_MASTER_KEYSET" == operation:
            LEAF_IP_CARD_MASTER_KEYSET = setting[1].strip()
        elif "LEAF_IP_CARD_WRITE_KEYSET" == operation:
            LEAF_IP_CARD_WRITE_KEYSET = setting[1].strip()
        elif "LEAF_IP_KS1_OCPSK_KEYSET" == operation:
            LEAF_IP_KS1_OCPSK_KEYSET = setting[1].strip()
        elif "LEAF_IP_KS1_READ_KEYSET" == operation:
            LEAF_IP_KS1_READ_KEYSET = setting[1].strip()
        elif "LEAF_IP_KS2_OCPSK_KEYSET" == operation:
            LEAF_IP_KS2_OCPSK_KEYSET = setting[1].strip()
        elif "LEAF_IP_KS2_READ_KEYSET" == operation:
            LEAF_IP_KS2_READ_KEYSET = setting[1].strip()
        elif "LEAF_IP_KS3_OCPSK_KEYSET" == operation:
            LEAF_IP_KS3_OCPSK_KEYSET = setting[1].strip()
        elif "LEAF_IP_KS3_READ_KEYSET" == operation:
            LEAF_IP_KS3_READ_KEYSET = setting[1].strip()
        elif "LEAF_KHSENC1_KEYS" == operation:
            LEAF_KHSENC1_KEYS = setting[1].strip()
        elif "M2G_ACD_LEAF_KEYS" == operation:
            LEAF_KHSENC1_KEYS = setting[1].strip()
        elif "LEAF_KHSENC2_KEYS" == operation:
            LEAF_KHSENC2_KEYS = setting[1].strip()
        elif "M2G_GENERIC_KEYS" == operation:
            LEAF_KHSENC2_KEYS = setting[1].strip()
        elif "LEAF_HSREAD_KEYS" == operation:
            LEAF_HSREAD_KEYS = setting[1].strip()
        elif "CUSTOMER_CONFIG_KEYS" == operation:
            # CUSTOMER CONFIG KEY REPLACES THE LEAF_HSREAD_KEYS 
            LEAF_HSREAD_KEYS = setting[1].strip()
        elif "LEAF_KBLEENC2_KEYS" == operation:
            LEAF_KBLEENC2_KEYS = setting[1].strip()
        elif "CUSTOMER_DEFINED_KEYS" == operation:
            # CUSTOMER CONFIG KEY REPLACES THE LEAF_KBLEENC2_KEYS 
            LEAF_KBLEENC2_KEYS = setting[1].strip()
        elif "NFC_KM1_KEYS" == operation:
            NFC_KM1_KEYS = setting[1].strip()
        elif "NFC_KC1_KEYS" == operation:
            NFC_KC1_KEYS = setting[1].strip()
        elif "NFC_KM2_KEYS" == operation:
            NFC_KM2_KEYS = setting[1].strip()
        elif "NFC_KC2_KEYS" == operation:
            NFC_KC2_KEYS = setting[1].strip()
        elif "NFC_MP0_KEYS" == operation:
            NFC_MP0_KEYS = setting[1].strip()
        elif "NFC_MC0_KEYS" == operation:
            NFC_MC0_KEYS = setting[1].strip()
        elif "EXT_BUILD_INDEX" == operation:
            if setting[1].startswith("0x"):
                config.appendOpt(
                    wl.SPECIAL_FEATURES_INDEX, int(setting[1].strip(), 16) & wl.BUILD_EXT_MASK
                )
                config.appendOpt(wl.BUILD_INDEX, int(setting[1].strip(), 16) & wl.FW_BUILD_MASK)
            else:
                config.appendOpt(
                    wl.SPECIAL_FEATURES_INDEX, int(setting[1].strip(), 10) & wl.BUILD_EXT_MASK
                )
                config.appendOpt(wl.BUILD_INDEX, int(setting[1].strip(), 10) & wl.FW_BUILD_MASK)
        else:
            try:
                setOptName = eval("wl." + setting[1].strip())
            except (AttributeError, SyntaxError):
                setOptName = setting[1].strip()
            try:
                print(setting)
                tempStr = setting[2].strip()
                if tempStr.startswith("0x"):
                    setOptVal = int(tempStr[2:], 16)
                else:
                    firstAlpha = re.search(r"[A-Z]", tempStr, re.I)
                    if firstAlpha is not None:
                        idx = firstAlpha.start()
                        setOptVal = eval(tempStr[:idx] + "wl." + tempStr[idx:])
                    else:
                        setOptVal = eval("wl." + tempStr)
            except (AttributeError, SyntaxError):
                setOptVal = setting[2].strip()
            if "APP" == operation:
                if "ALL" == setOptName:
                    config.setAllCardTypeApp(setOptVal)
                    print("setting all to none")
                else:
                    try:
                        setVal3 = eval("wl." + setting[3].strip())
                    except (AttributeError, SyntaxError):
                        setVal3 = int(setting[3].strip())
                    config.setCardTypeApp(int(setOptName), safe_int_eval(setOptVal), int(setVal3))
            elif "RF" == operation:
                config.setRf(int(setOptName), safe_int_eval(setOptVal))
            elif "OPT" == operation:
                config.setOpt(safe_int_eval(setOptName), safe_int_eval(setOptVal))
            elif "OPT_AUG" == operation:
                # print(setting)
                config.appendOpt(setOptName, safe_int_eval(setOptVal))
            elif "OPT_MASK" == operation:
                config.maskOpt(setOptName, safe_int_eval(setOptVal) & 0xFFFF)
            elif "OPT_MASK_INV" == operation:
                config.maskOpt(setOptName, ~(safe_int_eval(setOptVal)) & 0xFFFF)
            elif "LED" == operation:
                loopCount = 0
                final = 0
                for j in setting[1:]:
                    try:
                        led = eval("wl." + j.strip())
                    except (AttributeError, SyntaxError):
                        led = int(j.strip(), 16)
                    if (loopCount - 1) >= 0:
                        final |= led << ((loopCount - 1) * 2)
                    else:
                        final |= led
                    loopCount += 1
                config.setOpt(safe_int_eval(wl.LED_OPTIONS_1_INDEX), safe_int_eval(final))
            elif "HW" == operation:
                if "TYPE" == setOptName:
                    config.setType(setOptVal)
                elif "ASK" == setOptName:
                    if setOptVal == "ENABLE":
                        config.enableAskSupport()
                    else:
                        config.disableAskSupport()
            elif "BS_AUG" == operation:
                config.augBS(setOptName, safe_int_eval(setOptVal))
            elif "BS_SET" == operation:
                config.setBS(setOptName, safe_int_eval(setOptVal))
            elif "BS_FILTER_MASK" == operation:
                config.setFilterMask(int(setOptName), safe_int_eval(setOptVal))
            elif "BS_FILTER_VALUE" == operation:
                config.setFilterValue(int(setOptName), safe_int_eval(setOptVal))
            elif "MOBILE" == operation:
                config.setMobile(setOptName, "SET", safe_int_eval(setOptVal))
            elif "MOBILE_MASK" == operation:
                config.setMobile(setOptName, "MASK", safe_int_eval(setOptVal))
            elif "MOBILE_AUG" == operation:
                config.setMobile(setOptName, "AUG", safe_int_eval(setOptVal))
            # TODO: need to figure out key import

            # elif ( "KEY"== operation):
            #     config.setKey(int(setOptName), setOptVal)
            # elif ("GKEY" == operation):
            #    config.setGuardianKey(setOptName)
            else:
                print("Error Unknown operation: ", operation)
                sys.exit("Error Unknown operation: ")
    # print("config is ", config.dump())
    encoders = [PROD_TEST_ENC_KEY, EXT_MEM_KEYSET]

    proxAsk = config.OpSettings[wl.OPERATION_INDEX] & wl.ENABLE_ASK_RF
    proxFsk = config.OpSettings[wl.OPERATION_INDEX] & wl.ENABLE_FSK_RF
    proxMtiAsk = config.OpSettings[wl.EXT_OPERATION_INDEX] & wl.ENABLE_MTI_ASK_RF

    # set these flags for all configs
    # config.OpSettings[wl.SPECIAL_FEATURES_INDEX] |= wl.LEAF_IP_SKIP_HS_FILE_MASK

    # if not enckey.startswith("GENERIC"):
    #     encoders.append(enckey)
    today = date.today()
    datestring = today.isoformat()
    for encodeKey in encoders:
        for hw_variant in hw_types:
            # prefix = sys.argv[1].rfind("/")
            if "/" in sys.argv[1]:
                prefix = sys.argv[1].split(".csv")[0][sys.argv[1].rfind("/") :]
            else:
                prefix = "/" + sys.argv[1].split(".csv")[0]
            finalFile = (
                "../configs/nonApproved/WS"
                + prefix
                + "_"
                + str(hw_variant)
                + "_V_{:x}_{:x}_{:x}_{:x}".format(
                    wl.FW_MAJOR_VERSION,
                    wl.FW_MINOR_VERSION,
                    wl.FW_BUILD_NUMBER,
                    wl.FW_RELEASE_CANDIDATE,
                )
            )
            if PROD_TEST_ENC_KEY == encodeKey:
                finalFile += "_PT.bin"
            elif not encodeKey == EXT_MEM_KEYSET:
                finalFile += "_" + encodeKey + ".bin"
            else:
                finalFile += ".bin"

            config.maskOutOpt(wl.OPERATION_INDEX, wl.ENABLE_FSK_RF)
            config.maskOutOpt(wl.OPERATION_INDEX, wl.ENABLE_ASK_RF)
            config.maskOutOpt(wl.EXT_OPERATION_INDEX, wl.ENABLE_MTI_ASK_RF)
            config.maskOutOpt(wl.OPERATION_INDEX, wl.ENABLE_HF_RF)
            config.maskOutOpt(wl.OPERATION_INDEX, wl.ENABLE_BLE)

            # print (os.getcwd())
            # print(finalFile, hw_variant)
            config.setType(hw_variant)
            if hw_variant & 0x1:
                if wl.ENABLE_FSK_RF == proxFsk:
                    valid_config = config.appendOpt(wl.OPERATION_INDEX, wl.ENABLE_FSK_RF)
                if wl.ENABLE_ASK_RF == proxAsk:
                    valid_config = config.appendOpt(wl.OPERATION_INDEX, wl.ENABLE_ASK_RF)
                if wl.ENABLE_MTI_ASK_RF == proxMtiAsk:
                    # valid_config = config.appendOpt(wl.OPERATION_INDEX, wl.ENABLE_MTI_ASK_RF)
                    valid_config = config.appendOpt(wl.EXT_OPERATION_INDEX, wl.ENABLE_MTI_ASK_RF)

                if not valid_config:
                    continue
            if hw_variant & 0x2:
                valid_config = config.appendOpt(wl.OPERATION_INDEX, wl.ENABLE_HF_RF)
                if not valid_config:
                    continue
            if hw_variant & 0x4:
                valid_config = config.appendOpt(wl.OPERATION_INDEX, wl.ENABLE_BLE)
                if not valid_config:
                    continue
            try:
                files = open(finalFile, mode="w+b")
                # print ("HERE",FEATURE_MANAGEMENT_READ_KEYSET, FEATURE_MANAGEMENT_WRITE_KEYSET, LEAF_IP_READ_KEYSET)
                keyset = [
                    FEATURE_MANAGEMENT_READ_KEYSET,
                    FEATURE_MANAGEMENT_WRITE_KEYSET,
                    USER_APP_OCPSK_KEYSET,
                    USER_APP_READ_KEYSET,
                    USER_APP_CARD_MASTER_KEYSET,
                    USER_APP_CARD_WRITE_KEYSET,
                    EXT_MEM_KEYSET,
                    OSDP_KEYSET,
                    BLE_KEYSET,
                    MFC_KEYSET,
                    USER_APP2_K1_KEYSET,
                    USER_APP2_K2_KEYSET,
                    LEAF_IP_OCPSK_KEYSET,
                    LEAF_IP_READ_KEYSET,
                    LEAF_IP_CARD_MASTER_KEYSET,
                    LEAF_IP_CARD_WRITE_KEYSET,
                    LEAF_IP_KS1_OCPSK_KEYSET,
                    LEAF_IP_KS1_READ_KEYSET,
                    LEAF_IP_KS2_OCPSK_KEYSET,
                    LEAF_IP_KS2_READ_KEYSET,
                    LEAF_IP_KS3_OCPSK_KEYSET,
                    LEAF_IP_KS3_READ_KEYSET,
                    LEAF_KHSENC1_KEYS,
                    LEAF_KHSENC2_KEYS,
                    LEAF_HSREAD_KEYS,
                    LEAF_KBLEENC2_KEYS,
                    NFC_KM1_KEYS,
                    NFC_KC1_KEYS,
                    NFC_KM2_KEYS,
                    NFC_KC2_KEYS,
                    NFC_MP0_KEYS,
                    NFC_MC0_KEYS,
                ]
                if userkeys is None:
                    ret = load_blob(
                        blob_id=finalFile,
                        name=finalFile,
                        desc=finalFile,
                        signing="config",
                        operations=["factoryconfig"],
                        keyset=keyset,
                        signingkey=encodeKey,
                        data=config.dump(),  # base64.b64encode(config.dump()).decode("utf-8"),
                    )
                else:
                    ret = load_blob(
                        blob_id=finalFile,
                        name=finalFile,
                        desc=finalFile,
                        signing="config",
                        operations=["userkeys"],
                        keyset=keyset,
                        signingkey=userkeys,
                        data=config.dump(),  # base64.b64encode(config.dump()).decode("utf-8"),
                    )
                    if ret[0]:
                        write_user_keys(ret[1])
                    else:
                        print(
                            "no Data returned from SEQUOIA check that it is reachable and unlocked and that the file is correct",
                            sys.argv[1],
                        )

                    sys.exit("parsing complete got c from sequoia")

                if ret[0]:
                    # print("return value was " ,ret[1])
                    files.write(ret[1])
                    files.close()
                else:
                    print(
                        "no Data returned from SEQUOIA check that it is reachable and unlocked and that the file is correct",
                        sys.argv[1],
                    )
                    files.close()

                    sys.exit("parsing complete")

            except TypeError:
                print("invalid config type continue")
            finally:
                files.close()

    # # print("wrapping built configuraiton\n")
    # TAG = wl.TLV_TAG_FULL_FEATURE_SETUP
    # CFG_SIZE = 1024

    # # Full Feature Setup only for other configurations please refer to https://gitlab.com/WaveLynxTech/et-config/-/blob/master/Features.org
    # encapedFeatures = TAG.to_bytes(1, byteorder="little", signed=False)
    # encapedFeatures += CFG_SIZE.to_bytes(3, byteorder="little", signed=False)
    # encapedFeatures += config.dump()
    # # print("encap features is ", encapedFeatures)

    # #final container Taylor has something for the final envelope
    # # TODO
    # envelope = encapedFeatures
    # # now dump that into
    # outFile = sys.argv[1].rsplit(".", 1)[0] + "_preEnv.bin"
    # newfile = open(outFile, "wb")
    # newfile.write(envelope)
